name: CD Pipeline

on:
  push:
    branches: [master]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-release:
    name: Build the release
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.repository == 'sequence-toolbox/SeQUeNCe'
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: 'auto'
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Build wheel and tarball
        run: uv build
      - name: Store dist as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-release-package-dist
          path: dist/

  build-test-release:
    name: Build the test release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.repository == 'sequence-toolbox/SeQUeNCe'
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: 'true'
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Modify package name for TestPyPI
        run: |
          sed -i 's/^name = "sequence"/name = "ssequence"/' pyproject.toml
      - name: Build wheel and tarball for test
        run: uv build
      - name: Store test dist as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-test-package-dist
          path: dist/

  publish-to-pypi:
    name: Publish dist to PyPi
    if: github.event_name == 'release' && github.event.action == 'published' && github.repository == 'sequence-toolbox/SeQUeNCe'
    needs:
      - build-release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/sequence
    permissions:
      id-token: write

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v5
        with:
          name: python-release-package-dist
          path: dist/
      - name: Publish dist to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  publish-to-test-pypi:
    name: Publish dist to TestPyPi
    if: github.event_name == 'push' && github.repository == 'sequence-toolbox/SeQUeNCe'
    needs:
      - build-test-release
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/ssequence

    permissions:
      id-token: write

    steps:
      - name: Download all the test dists
        uses: actions/download-artifact@v5
        with:
          name: python-test-package-dist
          path: dist/
      - name: Publish dist to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: 'true'
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true